### ISSUE TITLE
我的世界报告错误

### ISSUE THREAD

**Issue by irkbyxfcqjelz** [Origins-Eternity/Evolution-Reset#2]
linux无法启动游戏这是我的世界报告错误
[minecraft-exported-crash-info-2023-07-22T18-30-09.zip](https://github.com/Origins-Eternity/Evolution-Reset/files/12136549/minecraft-exported-crash-info-2023-07-22T18-30-09.zip)

**Comment by Origins-Eternity** [comment]
是否尝试过重新安装或者换个启动器？我并没有在Linux系统上测试过客户端，但我的服务器在Linux系统上正常运行。

**Comment by irkbyxfcqjelz** [comment]
换过启动器但是依然报错

**Comment by irkbyxfcqjelz** [comment]
> 是否尝试过重新安装或者换个启动器？我并没有在Linux系统上测试过客户端，但我的服务器在Linux系统上正常运行。

换过启动器但是依然报错

**Comment by Origins-Eternity** [comment]
那试试关掉RandomPatches模组？如果依旧报错请把新的报告发我。

**Comment by irkbyxfcqjelz** [comment]
还是报错
[Uploading minecraft-exported-crash-info-2023-07-23T17-10-15.zip…]()

**Comment by Origins-Eternity** [comment]
报告没有上传成功？而且我看了一下你的java版本不太对。我的Linux服务器是这样的：
![image](https://github.com/Origins-Eternity/Evolution-Reset/assets/63846610/e5835a63-98df-4d1b-9cae-1a195ce3dfde)
和你的不太一样。你用这个试试？https://1drv.ms/u/s!AunQcasLIcJ_gbg-r4xAQJLYs_vpZw?e=Gnhrp7
![image](https://github.com/Origins-Eternity/Evolution-Reset/assets/63846610/87285b9e-a2b7-44ab-9fba-1dba3796c546)

**Comment by irkbyxfcqjelz** [comment]
> 报告没有上传成功？而且我看了一下你的java版本不太对。我的Linux服务器是这样的： ![image](https://user-images.githubusercontent.com/63846610/255442543-e5835a63-98df-4d1b-9cae-1a195ce3dfde.png) 和你的不太一样。你用这个试试？https://1drv.ms/u/s!AunQcasLIcJ_gbg-r4xAQJLYs_vpZw?e=Gnhrp7 ![image](https://user-images.githubusercontent.com/63846610/255442702-87285b9e-a2b7-44ab-9fba-1dba3796c546.png)

使用你的Java版本依然报错
但是使用修改的Java版本（FXjava）可以启动!

**Comment by irkbyxfcqjelz** [comment]
使用你提供的Java依然报错
但是我找来了修改版本javaFX没有报错可以正常启动
